on:
  workflow_call:
    inputs:
      RELEASE_REVISION:
        required: true
        type: string
      ECR_REPOSITORY:
        required: true
        type: string
      DOCKER_FILE:
        required: true
        type: string
      GENERATE_SSL_KEY:
        required: false
        type: boolean

name: Build and push docker image

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v6
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}
        role-skip-session-tagging: true

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: true

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Gnerate SSL key
      if: ${{ inputs.GENERATE_SSL_KEY }}
      run: |
        openssl genrsa -out private.key 2048
        openssl rsa -in private.key -pubout -out public.key

    - name: Build & Push Image
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_REVISION: ${{ inputs.RELEASE_REVISION }}
        RELEASE_IMAGE: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ECR_REPOSITORY }}:${{ inputs.RELEASE_REVISION }}
      run: |
        docker buildx build \
          -t ${{ inputs.ECR_REPOSITORY }}:${{ inputs.RELEASE_REVISION }} \
          -f ${{ inputs.DOCKER_FILE }} \
          --build-arg GIT_TAG_VERSION=${{ inputs.RELEASE_REVISION }} \
          --cache-from type=gha \
          --cache-to type=gha,mode=max \
          --load \
          .
        docker tag ${{ inputs.ECR_REPOSITORY }}:${{ inputs.RELEASE_REVISION }} ${{ env.RELEASE_IMAGE }}
        docker push ${{ env.RELEASE_IMAGE }}